### PR TITLE
First stab at updating codes

### PR DESCRIPTION
**Pull request by GrantMeStrength**
Hopefully this works..

### CODE REVIEW

**Comment by GrantMeStrength** [comment]
Thanks. Hope some of it is useful.

* Ah yes, should be "Wi-Fi"
* Your tech, your name :-)
* I am thinking of writing a separate general manual for retro 8080/Z80 based devices with things to try and do, and publishing that in the old-school format. Maybe that'd be a better way to go.

**Comment by GrantMeStrength** [comment]
BTW, as I look through the instructions again without watching the video as I go, it's clear there is a real need for photographs - in particular, I would say at the least:

* Photograph of all components, identifying ESP, named pieces of acrylic, front and back of cct board
* Photograph of where specific ICs go on the board, and USP in location
* Photograph of the SMD in place (link to SMD soldering tips)
* Photograph of LED mounting using the guide
* Photograph of the "sandwich" of layers that make up the final assembly.

I think these photos would help a lot!

**Comment by dmcnaugh** [comment]
John, I've only just noticed that you made edits for the assembly guide too. They look great, although I think I spotted a typo.

I'll break out the camera and get some more photos as you suggest.
All the components and parts are now in the BOM. I added the missing ones a few days ago.

So whats the best workflow? 
1. Do I just accept the PR and make the changes I see before promoting to the live site?
2. Do you edit the PR so its ready to merge and promote direct?

Either way works for me, what

**Comment by GrantMeStrength** [comment]
Whatever works for you - the way I took it, you would look at versions side-by-side and just pick whatever text you wanted (preferably the parts without typos!). I definitely think photos will help folks. Now you need to add some metrics to measure success, using page view counts and a CSAT indicator.. no wait.. I'm not at work.. not at work..

**Comment by dmcnaugh** [comment]
John, I have manually merged the majority of your proposed changes (along with a few edits) into the source files and pushed to the live site. Take a look and see if there is anything you'd change.

I am yet to add the suggested photos.

**Pull request closed without merging**
